spring:
  application:
    name: student_manager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentManager?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
server:
  port: 8080